In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('ai_impact.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4706 entries, 0 to 4705
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Job titles         4706 non-null   object
 1   AI Impact          4706 non-null   object
 2   Tasks              4706 non-null   int64
 3   AI models          4706 non-null   int64
 4   AI_Workload_Ratio  4706 non-null   float64
 5   Domain             4706 non-null   object
dtypes: float64(1), int64(2), object(3)
memory usage: 220.7+ KB

In [4]:
df['AI Impact'] = df['AI Impact'].str.rstrip('%').astype(float)

In [8]:
df['Model/Task Ratio']=df['AI models']/df['Tasks']

In [26]:
high_impact=df.loc[df['AI Impact']>=70]
high_impact.head()

,Job titles,AI Impact,Tasks,AI models,AI_Workload_Ratio,Domain,Model/Task Ratio,deviation
0,Communications Manager,98.0,365,2546,0.143362,Communication & PR,6.975342,-1.344639
1,Data Collector,95.0,299,2148,0.139199,Data & IT,7.183946,-1.553243
2,Data Entry,95.0,325,2278,0.142669,Administrative & Clerical,7.009231,-1.378527
3,Mail Clerk,95.0,193,1366,0.141288,Leadership & Strategy,7.077720,-1.447017
4,Compliance Officer,92.0,194,1369,0.141709,Medical & Healthcare,7.056701,-1.425998

In [31]:
avg_ratio=df['Model/Task Ratio'].mean()
print(avg_ratio)
df['deviation']=avg_ratio-df['Model/Task Ratio']
high_impact.head()

5.630703466293158

,Job titles,AI Impact,Tasks,AI models,AI_Workload_Ratio,Domain,Model/Task Ratio,deviation
0,Communications Manager,98.0,365,2546,0.143362,Communication & PR,6.975342,-1.344639
1,Data Collector,95.0,299,2148,0.139199,Data & IT,7.183946,-1.553243
2,Data Entry,95.0,325,2278,0.142669,Administrative & Clerical,7.009231,-1.378527
3,Mail Clerk,95.0,193,1366,0.141288,Leadership & Strategy,7.077720,-1.447017
4,Compliance Officer,92.0,194,1369,0.141709,Medical & Healthcare,7.056701,-1.425998

In [19]:
#result = df.loc[df.groupby('Job titles')['AI Impact'].idxmax()]
#print(result[['Job titles','AI Impact','Tasks','AI models']].head(30))

In [34]:
df[round(df['Model/Task Ratio'],2)==round(avg_ratio,2)]

,Job titles,AI Impact,Tasks,AI models,AI_Workload_Ratio,Domain,Model/Task Ratio,deviation
2037,Ndt Technician,30.0,161,907,0.177508,Construction,5.633540,-0.002837
2105,Elevator Technician,30.0,128,721,0.177531,Supply Chain & Logistics,5.632812,-0.002109
2991,Payroll Accountant,20.0,223,1255,0.177689,Data & IT,5.627803,0.002901
2992,Payroll Analyst,20.0,223,1255,0.177689,Administrative & Clerical,5.627803,0.002901